---
show-messages-onjoin: true
force-hub: false
enable-hub-message: true
force-spawn: false
enable-spawn-message: true
enable-aliases: true
teleport-on-death: 1
hub-server:
  enabled: false
  name: External Server
  host: 127.0.0.1
  port: 19132
hub:
  world: SkyBlockSpawn
  X: 0.454000
  "Y": 65.000000
  Z: 0.372700
  Yaw: 269.403839
  Pitch: -2.034683
...
