---
datetime-format: "H:i:s"
Motd:
  update-timeout: 1
  custom: false
  message: "§l§7[ §a{TIME}§7 ] §bName Server"
OutdatedClient:
  custom: true
  message: "§l§cPhiên Bản §aMinecraft §c Của Bạn Không Tương Thích Với Server Này!\n§7[§b1.10.x§7]"
OutdatedServer:
  custom: true
  message: "§l§cRất Tiếc! Máy Chủ Đã Bị Lỗi!"
WhitelistedServer:
  custom: true
  message: "§c§lMáy Chủ Này Đã Được Đưa Vào §fDanh Sách Trắng!"
FullServer:
  custom: true
  message: "§l§e{PLAYER}&b, Server Này Đã Đầy &c[{TOTALPLAYERS}/{MAXPLAYERS}]&b!\n&l&dHãy Vào Lại Sau"
FirstJoin:
  enable: true
  message: "• §7[ §6{PLAYER} §7]§e Lần Đầu Tiên Vào §cServer §f(｡’▽’｡)"
Join:
  hide: false
  custom: true
  message: "• §7[ §6{PLAYER} §7]§b Đã Vào §cServer §f(･´з`･)"
Quit:
  hide: false
  custom: true
  message: "§f• §7[ §6{PLAYER} §7]§e Đã Thoát Khỏi §cServer §f(*>.<*)"
WorldChange:
  enable: true
  message: "• §7[ §6{PLAYER} §7]&e Di chuyển &c{ORIGIN}&e sang &a{TARGET}"
Death:
  hide: false
  custom: true
  message: "• §7[ §6{PLAYER} §7] §bĐã Chết Vì Lí Do Nào Đó §f(ㄒoㄒ)"
  death-contact-message:
    hide: false
    custom: true
    message: "§7[ §6{PLAYER} §7] §cĐã Chết Bởi §e{BLOCK} §f(✖╭╮✖)"
  kill-message:
    hide: false
    custom: true
    message: "§7[ §6{PLAYER} §7] &dĐã Bị Chết Bởi &c{KILLER} §fΣ(っﾟДﾟ；)っ"
  death-projectile-message:
    hide: false
    custom: true
    message: "§7[ §6{PLAYER} §7] §aĐã Bị Nát ASS Bởi §e{KILLER} §eDùng Cung §fノ( º _ ºノ) "
  death-suffocation-message:
    hide: true
    custom: false
    message: "§l§7[ §6{PLAYER} §7] §aNghẹt Thở Đến Chết §f(✖﹏✖)"
  death-fall-message:
    hide: false
    custom: true
    message: "§l§7[ §6{PLAYER} §7] §bĐã Bị Chết Vì Rơi Xuống Một Độ Cao Nào Đó §fΣ( ° △ °|||)"
  death-fire-message:
    hide: false
    custom: true
    message: "§7§l[ §6{PLAYER} §7] §eĐã Bị Chết Vì Cháy §f( ╯_╰ )"
  death-on-fire-message:
    hide: false
    custom: true
    message: "§7§l[ §6{PLAYER} §7] §6Đã Bị Chết Vì Đứng Quá Lâu Trong Lửa §f( ●︿● )"
  death-lava-message:
    hide: false
    custom: true
    message: "§l§7[ §6{PLAYER} §7] §aBị Chết Dưới Lava §fっ╥╯﹏╰╥c"
  death-drowning-message:
    hide: false
    custom: true
    message: "§l§7[ §6{PLAYER} §7] §bĐã Bị Chết Đuối Dưới Nước §f(๑-﹏-๑)"
  death-explosion-message:
    hide: false
    custom: true
    message: "§l§7[ §6{PLAYER} §7] §2Đã Bị Chết Vì Nổ §f( ￣へ￣ )"
  death-void-message:
    hide: false
    custom: true
    message: "§7§l[ §6{PLAYER} §7] §9Đã Bị Rơi Ra Ngoài Thế Giới Vì Lí Do Nào Đó §f(ㄒoㄒ)"
  death-suicide-message:
    hide: true
    custom: false
    message: "&c{PLAYER} committed suicide"
  death-magic-message:
    hide: false
    custom: true
    message: "§7§l[ §6{PLAYER} §7] §5Bị Chết Bằng Một Ma Thuật Nào Đó §f≥﹏≤"
...
