---
# AutoClearLagg (ACL) Config

# Seconds between each clear lagg
seconds: 1000

# Entities to clear
clear:
  items: true
  mobs: true
  exempt: # Array of entities not to clear
    - Zombie
    - Pig

messages:
  time-left: " §l§c•[§r§bSnow §6BE§r§c]§r §aChuẩn bị dọn rác sau {SECONDS} giây nữa"
  entities-cleared: " §l§c•[§r§bSnow §6BE§r§c]§r §6Đã dọn {COUNT} vật phẩm"

# Countdown times
times: [30, 10,]
...